name: observatory-crate-workflow
on:
  workflow_dispatch:
jobs:
  job:
    runs-on: ubuntu-latest
    env:
      ROCRATE_PROFILE_URI: https://data.emobon.embrc.eu/observatory-profile/latest
      WATER_LOGSHEET_URL: https://docs.google.com/spreadsheets/d/1mEi4Bd2YR63WD0j54FQ6QkzcUw_As9Wilue9kaXO2DE/edit?usp=sharing
      SEDIMENT_LOGSHEET_URL: https://docs.google.com/spreadsheets/d/1zc0bZdpl-Eoi35lI_5BGkElbscplyQRyNPLkSgeEyEQ/edit?usp=sharing
      DATA_QUALITY_CONTROL_THRESHOLD_DATE: 31/12/2022
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: download
        uses: emo-bon/logsheet-downloader-action@master
      - name: git-auto-commit-action
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: update on behalf of logsheet-downloader-action
      - name: data-quality-control-action
        uses: emo-bon/data-quality-control-action@main
        env:
          PAT: ${{ secrets.GITHUB_TOKEN }}
          REPO: ${{ github.repository }}
          ASSIGNEE: bulricht
      - name: git-auto-commit-action
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: update on behalf of data-quality-control-action
      - name: semantic-uplifting-action
        uses: emo-bon/semantic-uplifting-action@main
        env:
          PROFILE: ${{ env.ROCRATE_PROFILE_URI }}
      - name: git-auto-commit-action
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: update on behalf of semantic-uplifting-action
      - name: rocrate-to-pages
        uses: vliz-be-opsci/rocrate-to-pages@latest
        with:
          multiple_rocrates: true
          release_management: false
          include_draft: false
          index_html: false
          space_to_pages_homepage: https://data.emobon.embrc.eu
      - name: actions-gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./unicornpages
